name: Run Scripts Every 5 Minutes

on:
  workflow_dispatch:  # אפשרות להפעלה ידנית
  schedule:
    - cron: '*/5 * * * *'  # הפעלה כל 5 דקות

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 urllib3

    - name: Set up NetFree certificate
      run: |
        sudo mkdir -p /ProgramData/NetFree/CA
        sudo touch /ProgramData/NetFree/CA/netfree-ca-list.crt

    - name: Run chatfon.py
      env:
        YEMOT_USERNAME: ${{ secrets.0747098744 }}
        YEMOT_PASSWORD: ${{ secrets.123456 }}
      run: |
        echo "Starting chatfon.py"
        python chatfon.py

    - name: Run appfon.py
      env:
        YEMOT_USERNAME: ${{ secrets.0747098744 }}
        YEMOT_PASSWORD: ${{ secrets.123456 }}
      run: |
        echo "Starting appfon.py"
        python appfon.py

    - name: Run send_chat
      env:
        YEMOT_USERNAME: ${{ secrets.0747098744 }}
        YEMOT_PASSWORD: ${{ secrets.123456 }}
      run: |
        echo "Starting send_chat"
        python send_chat
